[project]
name = "spaceup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown-it-py>=4.0.0",
    "mistune>=3.1.3",
]

[dependency-groups]
dev = [
    "bs4>=0.0.2",
    "pytest>=8.4.1",
]
